### PR TITLE
Fix bug with dual deploy path

### PR DESCRIPTION
**Pull request by tarasbilohan**
Config example
```
module.exports = {
  pluginOptions: {
    s3Deploy: {
      ...
      deployPath: '/some-path/',
      ...
    }
  }
}
```
All files uploaded to path **/some-path/some-path/...**

### CODE REVIEW

**Comment by omanizer** [comment]
I've confirmed this PR fixes the issue.  Any idea when this gets merged?

**Comment by demiro** [comment]
PLEASE, pretty please, merge this... is a huge issue!

**Comment by nicekiwi** [comment]
This does not solve the issue, it just disables the deployPath feature.

**Comment by nicekiwi** [comment]
@demiro has this issue been resolved the issue for you in the rc4 release?

**Comment by tarasbilohan** [comment]
@nicekiwi version 4.0.0-rc4 works for me.
Changes from commit https://github.com/multiplegeorges/vue-cli-plugin-s3-deploy/commit/cf0746f356b9d1dfac7413bafdc8ca53f7624ab1#diff-5faf43f81de05c8fa81c690320ee8f4a have fixed the issue.
This pull request is not actual.

**Comment by demiro** [comment]
> @demiro has this issue been resolved the issue for you in the rc4 release?

yes it is... it is working now.  thanks for fixing so quick

**Pull request closed without merging**
