### PR TITLE
[Doc] Update doc based on configuration.js

### PR DESCRIPTION
**Pull request by Roriz**

### CODE REVIEW

**Comment by nicekiwi** [comment]
Thanks for the suggestion, but RC4 and 5 area a major refactor and all of this is changing. Right now I thinking:

```
cachePerFile = [
  { pattern: [ '*.js' ], cache: 'max84000' }
]
```

**Comment by Roriz** [comment]
Your suggestion is per file or per pattern? I think the current pattern with object is clear and obviously.

**Comment by Roriz** [comment]
Has any estimate for this feature come to release? I really need that

**Comment by nicekiwi** [comment]
The Cache pattern needs to be an array is the issue. The pattern can include any number of files matched, by name or extension or anything else `micromatch` can match. When? Soon I hope. I've removed a number of features from earlier RC releases so the lib should be a lot easier to maintain and test (hopefully).

**Comment by nicekiwi** [comment]
I'd rather explicitly name object properties than mess around with key names as values, espessially when dealing with TypeScript.

**Pull request closed without merging**
