### PR TITLE
Add support for public-read permissions on all files

### PR DESCRIPTION
**Pull request by nicekiwi**
#17

### CODE REVIEW

**Comment by nicekiwi** [comment]
Crap, didn't mean to reformat the tab widths.

**Comment by multiplegeorges** [comment]
Thanks for the pull request!
I am using the [Standard JS](https://standardjs.com/) formatting style for my code. 

Could you please re-format according to that standard and push the changes?

**Comment by nicekiwi** [comment]
Joys of AWS :p will do! :)

**Comment by nicekiwi** [comment]
@multiplegeorges done. :)

**Comment by vongkim** [comment]
I think the public read ACL should also apply to files being copied in the `setCacheControl` method as well.

e.g something like this
```
  async function setCacheControl (bucket, fileKey, publicReadFiles) {
    // Copies in-place while updating the metadata.
    let params = {
      CopySource: `${bucket}/${fileKey}`,
      Bucket: bucket,
      Key: fileKey,
      CacheControl: 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0',
      ContentType: contentTypeFor(fileKey),
      MetadataDirective: 'REPLACE'
    }
    if (publicReadFiles) {
      params['ACL'] = 'public-read'
    }
    return new Promise((resolve, reject) => {
      s3.copyObject(params, function (err, data) {
        if (err) {
          reject(err)
        } else {
          resolve(data)
        }
      })
    })
  }
```

**Comment by nicekiwi** [comment]
Good call! Will add.

**Comment by nicekiwi** [comment]
Though I’m not sure why that function is even being used when cache control can be set in the upload directly for PWA files

**Comment by nicekiwi** [comment]
I'll push this, as the MetadataDirective REPLACE will reset the ACL to private, but will also make another PR to rework the cache control updates into the uploadFile function.

**Comment by nicekiwi** [comment]
Included in #37

**Pull request closed without merging**
